
driver.get(self.base_url + "/cas-server/login?service=http://boss.qa.great-tao.com/cas")
driver.find_element_by_id("username").clear()
driver.find_element_by_id("username").send_keys("yuanjunling")
driver.find_element_by_id("password").clear()
driver.find_element_by_id("password").send_keys("1234")
driver.find_element_by_id("captcha").clear()
driver.find_element_by_id("captcha").send_keys("3086")
driver.find_element_by_name("submit").click()
driver.find_element_by_link_text(u"BOSSϵͳ").click()
driver.find_element_by_link_text(u"��������").click()
driver.find_element_by_link_text(u"�������").click()
Select(driver.find_element_by_id("type")).select_by_visible_text(u"�ɹ�����")
Select(driver.find_element_by_id("source")).select_by_visible_text(u"��������������Ӫ��")
driver.find_element_by_id("sourceRemark").clear()
driver.find_element_by_id("sourceRemark").send_keys("sd fsdf sdf")
Select(driver.find_element_by_id("roleBack")).select_by_visible_text(u"�ɹ���")
driver.find_element_by_id("company").clear()
driver.find_element_by_id("company").send_keys("ddddddd")
driver.find_element_by_id("contact").clear()
driver.find_element_by_id("contact").send_keys("dddd")
driver.find_element_by_id("position").clear()
driver.find_element_by_id("position").send_keys("ddddd")
driver.find_element_by_id("tel").clear()
driver.find_element_by_id("tel").send_keys("fffff")
driver.find_element_by_id("other").clear()
driver.find_element_by_id("other").send_keys("yuannnn")
driver.find_element_by_id("content").clear()
driver.find_element_by_id("content").send_keys("beizhu")
driver.find_element_by_id("btn-addAttach").click()
# ERROR: Caught exception [Error: locator strategy either id or name must be specified explicitly.]
driver.find_element_by_id("submit").click()
